# -*- coding: utf-8 -*-
"""LVADSUSR68_Akshansh_lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mGTYku48XnQ0miEgwGDNo8_0BGd-tGxI
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
booking_data = pd.read_csv('booking.csv')
booking_data.head()
missing_values_booking = booking_data.isnull().sum()
missing_values_booking
duplicates_booking = booking_data.duplicated().sum()
duplicates_booking
import seaborn as sns
import matplotlib.pyplot as plt
fig, axs = plt.subplots(4, figsize=(5, 10))

sns.boxplot(booking_data['number of adults'], ax=axs[0]).set_title('Number of Adults Distribution')
sns.boxplot(booking_data['number of children'], ax=axs[1]).set_title('Number of Children Distribution')
sns.boxplot(booking_data['lead time'], ax=axs[2]).set_title('Lead Time Distribution')
sns.boxplot(booking_data['average price'], ax=axs[3]).set_title('Average Price Distribution')

plt.tight_layout()
plt.show()
# encodding
booking_data_encoded = pd.get_dummies(booking_data,
                        columns=['type of meal', 'room type', 'market segment type', 'booking status'], drop_first=True)
booking_data_encoded.drop(['Booking_ID', 'date of reservation'], axis=1, inplace=True)
booking_data_encoded
# Dividing the data
X_booking = booking_data_encoded.drop('booking status_Not_Canceled', axis=1)
y_booking = booking_data_encoded['booking status_Not_Canceled']
X_train_booking, X_test_booking, y_train_booking, y_test_booking = train_test_split(X_booking, y_booking, test_size=0.2, random_state=42)
X_booking.shape
y_booking.shape
model_booking = LogisticRegression(max_iter=10000)
model_booking.fit(X_train_booking, y_train_booking)
y_pred_booking = model_booking.predict(X_test_booking)

# Model Evaluation
accuracy = accuracy_score(y_test_booking, y_pred_booking)
precision = precision_score(y_test_booking, y_pred_booking)
recall = recall_score(y_test_booking, y_pred_booking)
f1 = f1_score(y_test_booking, y_pred_booking)
conf_matrix = confusion_matrix(y_test_booking, y_pred_booking)

print(f'Accuracy: {accuracy}\nPrecision: {precision}\nRecall: {recall}\nF1-Score: {f1}\nConfusion Matrix: \n{conf_matrix}')